/**
 * Copyright (c) HashiCorp, Inc.
 * SPDX-License-Identifier: MPL-2.0
 */

// generated by cdktf get
Object.defineProperty(exports, 'computer', { get: function () { return require('./computer'); } });
Object.defineProperty(exports, 'gplink', { get: function () { return require('./gplink'); } });
Object.defineProperty(exports, 'gpo', { get: function () { return require('./gpo'); } });
Object.defineProperty(exports, 'gpoSecurity', { get: function () { return require('./gpo-security'); } });
Object.defineProperty(exports, 'group', { get: function () { return require('./group'); } });
Object.defineProperty(exports, 'groupMembership', { get: function () { return require('./group-membership'); } });
Object.defineProperty(exports, 'ou', { get: function () { return require('./ou'); } });
Object.defineProperty(exports, 'user', { get: function () { return require('./user'); } });
Object.defineProperty(exports, 'dataAdComputer', { get: function () { return require('./data-ad-computer'); } });
Object.defineProperty(exports, 'dataAdGpo', { get: function () { return require('./data-ad-gpo'); } });
Object.defineProperty(exports, 'dataAdGroup', { get: function () { return require('./data-ad-group'); } });
Object.defineProperty(exports, 'dataAdOu', { get: function () { return require('./data-ad-ou'); } });
Object.defineProperty(exports, 'dataAdUser', { get: function () { return require('./data-ad-user'); } });
Object.defineProperty(exports, 'provider', { get: function () { return require('./provider'); } });

